### PR TITLE
Final revision prp

### PR DESCRIPTION
**Pull request by samyeru**
revised all the strings and finalized the translation

### CODE REVIEW

**Comment by Diskmaster** [comment]
You may want to review PPF and PRP's export. It appears english strings got reverted compared to the version in the repo. (You can do multiple commits to a pull request, just add an additional commit or two.)

**Comment by samyeru** [comment]
yes, it was wanted just like that. I relied on the italian map of fallout 4
and the names of the places i changed are the same as the translation of
roger's italian unofficial patch. so in conclusion the files I uploaded on
github are the final translation that you can also use in future versions.

Il giorno mar 31 mag 2022 alle ore 21:31 Diskmaster <
***@***.***> ha scritto:

**Comment by Diskmaster** [comment]
Alright, just seems odd. Thank you!

**Comment by samyeru** [comment]
so in short, I checked all the xml files and checked all the changed
strings on github and they are fine as I uploaded them in the final
revision.

Il giorno mar 31 mag 2022 alle ore 23:26 samuele sponsillo <
***@***.***> ha scritto:

**Pull request merged**
